## Version Selection for compose file
# https://docs.docker.com/compose/compose-file/#/versioning
version: '2'
services:
  web:
    image: node:${NODE_VERSION}
    working_dir: /apps/examples
    entrypoint: /apps/docker-entrypoint.sh
    command: node server/server.js
    environment:
     DEBUG: boot:test:*
    ports:
     - "80:3000"
    volumes:
     - .:/apps
    depends_on:
     - es
    restart: always
  es:
    image: elasticsearch:${ES_VERSION}
